export const restaurants = [
    {
        name : "Bistrot Landais",
        image : require("../assets/images/restaurants/bistrotLandais.png"),
        image_icon : require("../assets/images/restaurants/bistrotLandais_icon.png"),
        subtitle : "XXXYYYZZZ",
        description : ["Qu'il est chaud le soleil",
        "Quand nous sommes en vacances",
        "Y a d' la joie, des hirondelles",
        "C'est le sud de la France",
        "Papa bricole au garage",
        "Maman lit dans la chaise longue",
        "Dans ce joli paysage",
        "Moi, je me balade en tongs",
        "",
        "Que de bonheur!",
        "Que de bonheur!"],
    },
    {
        name : "Bistrot des Gascons",
        image : require("../assets/images/restaurants/desGascons.png"),
        image_icon : require("../assets/images/restaurants/desGascons_icon.png"),
        subtitle : "XXXYYYZZZ",
        description : ["Qu'il est chaud le soleil",
        "Quand nous sommes en vacances",
        "Y a d' la joie, des hirondelles",
        "C'est le sud de la France",
        "Papa bricole au garage",
        "Maman lit dans la chaise longue",
        "Dans ce joli paysage",
        "Moi, je me balade en tongs",
        "",
        "Que de bonheur!",
        "Que de bonheur!"],
    },
    {
        name : "Bistrot du sommelier",
        image : require("../assets/images/restaurants/duSommelier.png"),
        image_icon : require("../assets/images/restaurants/duSommelier_icon.png"),
        subtitle : "XXXYYYZZZ",
        description : ["Qu'il est chaud le soleil",
        "Quand nous sommes en vacances",
        "Y a d' la joie, des hirondelles",
        "C'est le sud de la France",
        "Papa bricole au garage",
        "Maman lit dans la chaise longue",
        "Dans ce joli paysage",
        "Moi, je me balade en tongs",
        "",
        "Que de bonheur!",
        "Que de bonheur!"],
    },
    {
        name : "Les fous de l'ile",
        image : require("../assets/images/restaurants/fousDeLIle.png"),
        image_icon : require("../assets/images/restaurants/fousDeLIle_icon.png"),
        subtitle : "XXXYYYZZZ",
        description : ["Qu'il est chaud le soleil",
        "Quand nous sommes en vacances",
        "Y a d' la joie, des hirondelles",
        "C'est le sud de la France",
        "Papa bricole au garage",
        "Maman lit dans la chaise longue",
        "Dans ce joli paysage",
        "Moi, je me balade en tongs",
        "",
        "Que de bonheur!",
        "Que de bonheur!"],
    },
    {
        name : "Villa 9-Trois",
        image : require("../assets/images/restaurants/villa9Trois.png"),
        image_icon : require("../assets/images/restaurants/villa9Trois_icon.png"),
        subtitle : "XXXYYYZZZ",
        description : ["Qu'il est chaud le soleil",
        "Quand nous sommes en vacances",
        "Y a d' la joie, des hirondelles",
        "C'est le sud de la France",
        "Papa bricole au garage",
        "Maman lit dans la chaise longue",
        "Dans ce joli paysage",
        "Moi, je me balade en tongs",
        "",
        "Que de bonheur!",
        "Que de bonheur!"],
    },
]