export const ships = [
    {
        name : "Aquilon",
        image : require("../assets/images/bateaux/aquilon.png"),
        image_icon : require("../assets/images/bateaux/aquilon_icon.png"),
        subtitle : "XXXYYYZZZ",
        description : ["Qu'il est chaud le soleil",
        "Quand nous sommes en vacances",
        "Y a d' la joie, des hirondelles",
        "C'est le sud de la France",
        "Papa bricole au garage",
        "Maman lit dans la chaise longue",
        "Dans ce joli paysage",
        "Moi, je me balade en tongs",
        "",
        "Que de bonheur!",
        "Que de bonheur!"],
    },
    {
        name : "De la brise",
        image : require("../assets/images/bateaux/deLaBrise.png"),
        image_icon : require("../assets/images/bateaux/deLaBrise_icon.png"),
        subtitle : "XXXYYYZZZ",
    },
    {
        name : "Gast Micher",
        image : require("../assets/images/bateaux/gastMicher.png"),
        image_icon : require("../assets/images/bateaux/gastMicher_icon.png"),
        subtitle : "XXXYYYZZZ",
    },
    {
        name : "Saphir",
        image : require("../assets/images/bateaux/saphir.png"),
        image_icon : require("../assets/images/bateaux/saphir_icon.png"),
        subtitle : "XXXYYYZZZ",
    },
]